ingest:
  data_dir: "./data"
  metadata_path: "./data/corpus.jsonl"
  base_embedding_url: "http://localhost:8001"

  chunk_size: 500
  chunk_overlap: 50
  max_bytes: 1024
  batch_size: 50

  milvus_uri: "http://localhost:19530"
  collection_name: "hybrid_demo"
  embedding_dim: 1024

# config.yaml

search_api:
  base_url: "http://localhost:8001"
  milvus_uri: "http://localhost:19530"
  collection_name: "hybrid_demo"
  dense_dim: 1024

  # FastAPI 服务相关
  host: "0.0.0.0"
  port: 8002
  reload: true

  # 默认搜索超参
  default_limit: 10
  default_sparse_weight: 1.0
  default_dense_weight: 1.0

  # Milvus search params
  metric_type: "IP"
  metric_params: {}
